### ISSUE TITLE
Component doesn't work in React 16.0.0-alpha6

### ISSUE THREAD

**Issue by jjant** [phil-r/react-native-looped-carousel#88]
The component yields an `this.updater.enqueueCallback` is not a function error, as react 16.0.0-alpha6 removes the callback functionality from `setState`.

**Comment by jjant** [comment]
The problem is the `_setCurrentPage` method:
```
 _setCurrentPage = (currentPage) => {
    this.setState({ currentPage }, () => {
      if (this.props.onAnimateNextPage) {
        // FIXME: called twice on ios with auto-scroll
        this.props.onAnimateNextPage(currentPage);
      }
    });
  }
```

The workaround I found was to do the following:
```
 _setCurrentPage = (currentPage) => {
    this.setState(() => ({ currentPage });
    this.setState(() => { this.props.onAnimateNextPage ? this.props.onAnimateNextPage(currentPage) : false });
  }
```

**Comment by ryanhomer** [comment]
I'm surprised that RN 0.43.x uses React 16.0.0-alpha.6 already. I'm also surprised that the current stable release of RN is 0.44 since it also uses the same version of React... while the current stable release of React is at 15.5.4.

@jjant Thanks for the proposed solution. I will investigate what's going on with React 16 viz-à-viz `setState` but until it becomes a stable release, not sure what action should be taken.
